# Base image
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Entry point using current directory as volume
CMD ["python", "main.py"]
